version: "3.3"

volumes:
  code: {}
  db: {}

services:
  nginx:
    container_name: gitpab-nginx
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - code:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - php
    restart: unless-stopped

  php:
    container_name: gitpab-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - code:/var/www/html
    environment:
      GITLAB_PRIVATE_TOKEN: ${token}
#      GITLAB_RESTRICTIONS_PROJECT_IDS: ${projects}
      GITLAB_HOST: "https://gitlab.com/"
      APP_LOCALE: en
    links:
      - db
    restart: unless-stopped

  db:
    container_name: gitpab-db
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gitpab
      POSTGRES_USER: gitpab
      POSTGRES_PASSWORD: gitpab
    restart: unless-stopped
